### ISSUE TITLE
Install instructions don't seem to work as written

### ISSUE THREAD

**Issue by sbecker-sgi** [TulsaBioinformaticsToolsmith/LtrDetector#1]
I'm trying to install in a docker container (ubuntu:14.04). Issues encountered:
1. After cloning, start.py is under /LtrDetector/src, not the root /LtrDetector. Where should this be run from?

2. Make is also under src

3. running "make tr" from /LtrDetector/src gives:
"/usr/local/bin/g++-8 -std=c++11 -g -O3 -fopenmp -fmessage-length=0  -c test/TestTr.cpp -o ../bin/TestTr.o
make: /usr/local/bin/g++-8: Command not found
make: *** [../bin/TestTr.o] Error 127"

4. Commenting out the top CXX line in the make file and uncommenting the one below it:
# CXX = /usr/local/bin/g++-8
CXX = /usr/bin/g++
Then make tr runs, but I don't see /LtrDetector/bin/LtrDetector:

root@022f22b0e9ff:/LtrDetector# cd bin
root@022f22b0e9ff:/LtrDetector/bin# ls -la
total 3664
drwxr-xr-x. 7 root root     104 Oct 24 16:47 .
drwxr-xr-x. 6 root root      72 Oct 24 16:45 ..
-rwxr-xr-x. 1 root root 3382267 Oct 24 16:47 TestTr
-rw-r--r--. 1 root root  368288 Oct 24 16:46 TestTr.o
drwxr-xr-x. 2 root root     138 Oct 24 16:46 exception
drwxr-xr-x. 2 root root      80 Oct 24 16:46 nonltr
drwxr-xr-x. 2 root root       6 Oct 24 16:45 test
drwxr-xr-x. 2 root root     272 Oct 24 16:47 tr
drwxr-xr-x. 2 root root     230 Oct 24 16:47 utility

**Comment by sbecker-sgi** [comment]
I also have the same issue with ubuntu:18.04 and /usr/bin/g++-8 as the compiler. No obvious errors, but no LtrDetector binary seems to be formed.

**Comment by josephvalencia** [comment]
1. You are correct that the start.py and Makefile belong to /src . The instructions have been updated accordingly. Please run it from its current location.
2.Verify that you have the GNU C++ compiler. with ``` g++ --version ```. If this command is not recognized use the command ``` sudo apt-get install g++ ``` to install the compiler.
3. On Ubuntu you must comment out the line that you did and uncomment the one underneath so that:
 CXX = /usr/bin/g++.
4. Start.py builds the directories within /bin, so you must run it before you "make tr"

**Comment by sbecker-sgi** [comment]
Thanks for the clarification and the updates to your package. Unfortunately, I still don't see the LtrDetector binary after compilation. Here are the contents of my LtrDetector/bin directory:

root@baead0b4607c:/LtrDetector/bin# ls -la
total 6888
drwxr-xr-x. 7 root root     104 Nov  1 16:14 .
drwxr-xr-x. 6 root root      72 Nov  1 16:11 ..
-rwxr-xr-x. 1 root root 6253488 Nov  1 16:14 TestTr
-rw-r--r--. 1 root root  797968 Nov  1 16:13 TestTr.o
drwxr-xr-x. 2 root root     138 Nov  1 16:13 exception
drwxr-xr-x. 2 root root      80 Nov  1 16:13 nonltr
drwxr-xr-x. 2 root root       6 Nov  1 16:11 test
drwxr-xr-x. 2 root root     272 Nov  1 16:14 tr
drwxr-xr-x. 2 root root     230 Nov  1 16:14 utility

Going through the Makefile in /LtrDetector/src, I don't see any code in there that would actually create a binary file called LtrDetector. Is TestTr the binary that I need to use?

**Comment by josephvalencia** [comment]
Great catch! Looks like I forgot to change the name of the binary in the Makefile. It has been changed

**Comment by sbecker-sgi** [comment]
I have verified that the changes now work. Thanks.
