### ISSUE TITLE
Repeatable crash

### ISSUE THREAD

**Issue by sbecker-sgi** [TulsaBioinformaticsToolsmith/LtrDetector#2]
The attached FASTA file causes a crash when run (alone or with other files in the -chromDir) with default parameters:
"terminate called after throwing an instance of 'std::out_of_range'"
[error_contig.txt](https://github.com/TulsaBioinformaticsToolsmith/LtrDetector/files/2553975/error_contig.txt)

GitHub will not permit me to upload a .fa file, so I just changed the extension to .txt for convenience.

I have found at least one other contig FASTA file that causes the same problem, and I am guessing that I will find more.

**Comment by rmhubley** [comment]
I also have the same problem.  At first I thought it only affected contigs smaller than the minLen parameter but I have a 7.9kb example that also gives this error.  Let me know if you would like any of my examples to track down this problem.

**Comment by rmhubley** [comment]
This fixed the problem for me.  It looks like the authors failed to handle the case where an array could be empty.   If spikes.size() evaluates to an unsigned number then subtracting one makes this a very large number.

```

diff --git a/src/tr/MatchTr.cpp b/src/tr/MatchTr.cpp
index e487d2b..d9a3f50 100644
--- a/src/tr/MatchTr.cpp
+++ b/src/tr/MatchTr.cpp
@@ -107,6 +107,8 @@ void MatchTr::cleanAndMerge(){
 void MatchTr::forwardMerge(){
     //int GAP_TOLERANCE = k;int init = scorer->getInitialScore();
     
+    if ( spikes.size() == 0 )
+       return;
     for (int i = 0; i < spikes.size()-1; i++)
        {
                char curr_type;
@@ -462,4 +464,4 @@ void MatchTr::bedFormat(int start, int end)
     }
     output.close();
 }
-}
\ No newline at end of file
+}

```

**Comment by josephvalencia** [comment]
The latest update to the software incorporated your fix to this bug. Thanks so much!
