### ISSUE TITLE
segmentation fault

### ISSUE THREAD

**Issue by ricardo-aaron** [TulsaBioinformaticsToolsmith/LtrDetector#4]
Hi.
the -fasta option name is confusing: I thought it meant path to the fasta file, including the fasta file name. And the result is a "segmentation fault core dumped" error. I though that because the instructions say there's a -chromDir option (which there isn't). Maybe rename to -fastadir?

**Comment by hani-girgis** [comment]
Yes, please use the -fasta not -chromDir. 

-fasta directory_including_files_with_fa_extention

A help message is printed with the command: ./LtrDetector -help

Let me know if you encounter any issues.
