### ISSUE TITLE
segmentation fault (core dumped)

### ISSUE THREAD

**Issue by barshadey** [TulsaBioinformaticsToolsmith/LtrDetector#7]
I am running LtrDetector with the following command:
./LtrDetector -fasta /home/Barsha/Downloads/LtrDetector-master/trail/LUXP01.fa -destDir /home/Barsha/Documents/result
----------------------------------------------------------------------------------------------------------------
I am getting this error:
Reading chromosome directory ...
Segmentation fault (core dumped)

**Comment by hani-girgis** [comment]
The -fasta parameter takes a directory containing files to be scanned. Files must have .fa extension (not .fasta). I would run the following command:

./LtrDetector -fasta /home/Barsha/Downloads/LtrDetector-master/trail -destDir /home/Barsha/Documents/result
