### ISSUE TITLE
Reading chromosome directory ... Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by Xiang-Leo** [TulsaBioinformaticsToolsmith/LtrDetector#8]
I meet the same question that when I try this progarm. The command just like this:
`./LtrDetector -fasta /mnt/c/Users/JieCui/Desktop/LTR_Detector/2747seqs.fasta -destDir /mnt/c/Users/JieCui/Desktop/LTR_Detector/result/`
Then it came a tip: 
Reading chromosome directory ...
Segmentation fault (core dumped)
How can I solve this problem?

**Comment by hani-girgis** [comment]
The -fasta parameter takes a directory containing files to be scanned. Files must have .fa extension (not .fasta). First, I would change the extension from .fasta to .fa. Second, I would run the following command:

./LtrDetector -fasta /mnt/c/Users/JieCui/Desktop/LTR_Detector/ -destDir /mnt/c/Users/JieCui/Desktop/LTR_Detector/result/
